name: Build example

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install Java ♨️
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build 🔧
        env:
          DEFOLD_BOB_SHA1: ${{ secrets.DEFOLD_BOB_SHA1 }}
        run: |
          lsb_release -a

          mkdir -p build/bundle

          # Download the latest bob.jar
          BOB_SHA1=${DEFOLD_BOB_SHA1:-$(curl -s 'https://d.defold.com/stable/info.json' | jq -r .sha1)}
          BOB_LOCAL_SHA1=$((java -jar build/bundle/bob.jar --version | cut -d' ' -f6) || true)
          if [ "${BOB_LOCAL_SHA1}" != "${BOB_SHA1}" ]; then wget --progress=dot:mega -O build/bundle/bob.jar "https://d.defold.com/archive/${BOB_SHA1}/bob/bob.jar"; fi
          java -jar build/bundle/bob.jar --version

          # Build the project
          java -jar build/bundle/bob.jar --email a@b.com --auth 123 --texture-compression true --bundle-output build/bundle/x86_64-linux --platform x86_64-linux --archive --variant headless resolve build bundle

          # Run the example
          ./build/bundle/x86_64-linux/zstd_example/zstd_example.x86_64 --config=bootstrap.exit_immediately=yes

      - name: Upload Artifact 📦
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: build/bundle/x86_64-linux/zstd_example
